
#### api này dùng để innit dử liệu tiết học nên  không dùng
POST http://localhost:8080/api/lessons
Content-Type: application/json

[
    {
        "lessonName":"Tiết 1",
        "timeStart":"07:30:00",
        "timeEnd":"08:05:00",
        "active":true
    },
    {
        "lessonName":"Tiết 2",
        "timeStart":"08:05:00",
        "timeEnd":"08:40:00",
        "active":true
    },
    {
        "lessonName":"Ra chơi",
        "timeStart":"08:40:00",
        "timeEnd":"09:10:00",
        "active":false
    },
    {
        "lessonName":"Tiết 3",
        "timeStart":"09:10:00",
        "timeEnd":"10:20:00",
        "active":true
    },
    {
        "lessonName":"Tiết 4",
        "timeStart":"09:45:00",
        "timeEnd":"10:20:00",
        "active":true
    },
    {
        "lessonName":"Tiết 5",
        "timeStart":"10:20:00",
        "timeEnd":"10:55:00",
        "active":true
    },
    {
        "lessonName":"Nghỉ trưa",
        "timeStart":"10:55:00",
        "timeEnd":"14:00:00",
        "active":false
    },
    {
        "lessonName":"Tiết 6",
        "timeStart":"14:00:00",
        "timeEnd":"14:35:00",
        "active":true
    },
    {
        "lessonName":"Tiết 7",
        "timeStart":"14:35:00",
        "timeEnd":"15:10:00",
        "active":true
    },
    {
        "lessonName":"Ra chơi",
        "timeStart":"15:10:00",
        "timeEnd":"15:40:00",
        "active":false
    },
    {
        "lessonName":"Tiết 8",
        "timeStart":"15:40:00",
        "timeEnd":"16:15:00",
        "active":true
    }
]


# các api cho driver sử dụng
#########################################################
POST http://localhost:8080/api/studentAttendenceCheckin
Content-Type: application/json

{
    "studentId":"HS-079-676-754",
    "driverId":"FPljf"

}
#########################################################
POST http://localhost:8080/api/studentAttendenceCheckout
Content-Type: application/json

{
    "studentId":"2d7c287356f719e555",
    "driverId":"QMFEE"

}
#########################################################
POST http://localhost:8080/api/teacherAttendenceCheckin
Content-Type: application/json

{
    "teacherId":"GV-001-688-065",
    "driverId":"FPljf"

}
#########################################################
POST http://localhost:8080/api/teacherAttendenceCheckout
Content-Type: application/json

{
    "teacherId":"MnB19",
    "driverId":"QMFEE"

}

#########################################################
// các api để test 
//Thêm test vào vị trí /api/test/....
//Thiêm thuộc tính currentTime vào khi gọi api
//ví dụ 
POST http://localhost:8080/api/test/teacherAttendenceCheckin
Content-Type: application/json

{
    "teacherId":"MnB19",
    "driverId":"Kh0sf",
    "currentTime": "09:15:25"

}

### get 1 báo cáo bạo lực học đường 
POST   http://localhost:8080/api/uploadImg
Content-Type: application/json

{
    "linkValue": "https://images2.thanhnien.vn/zoom/328_205/528068263637045248/2024/4/23/h1-1713758513228565995478-0-82-967-1629-crop-17138413199221229012940.jpg",
    "imgStatus": "đánh nhau",
    "driverId": "yln-176"
}

### get 1 báo cáo bạo lực học đường 
POST   http://localhost:8080/api/students
Content-Type: application/json

[
    {
        "fullName": "Đỗ Khắc An",
        "phone": 123456789,
        "gender": "Nam",
        "birthDate": 41275,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Trần Đặng Minh Anh",
        "phone": 123456789,
        "gender": "Nữ",
        "birthDate": 41276,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Nguyễn Kỳ Anh",
        "phone": 123456789,
        "gender": "Nam",
        "birthDate": 41277,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Nguyễn Lan Anh",
        "phone": 123456789,
        "gender": "Nữ",
        "birthDate": 41278,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Trần Nguyễn Minh Anh",
        "phone": 123456789,
        "gender": "Nam",
        "birthDate": 41279,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Nguyễn Trần Duy Anh",
        "phone": 123456789,
        "gender": "Nam",
        "birthDate": 41280,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Nguyễn Trần Hoàng Anh",
        "phone": 123456789,
        "gender": "Nam",
        "birthDate": 41281,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Phạm Nguyễn Hồng Ân",
        "phone": 123456789,
        "gender": "Nữ",
        "birthDate": 41282,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Vũ Thiên Ân",
        "phone": 123456789,
        "gender": "Nam",
        "birthDate": 41283,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Trà Gia Bảo",
        "phone": 123456789,
        "gender": "Nam",
        "birthDate": 41284,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Nguyễn Trần Minh Châu",
        "phone": 123456789,
        "gender": "Nữ",
        "birthDate": 41285,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Nguyễn Võ Thành Công",
        "phone": 123456789,
        "gender": "Nam",
        "birthDate": 41286,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Nguyễn Khưu Bách Du",
        "phone": 123456789,
        "gender": "Nam",
        "birthDate": 41287,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Nguyễn Hoài Gia Hân",
        "phone": 123456789,
        "gender": "Nữ",
        "birthDate": 41288,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Nguyễn Ngọc Gia Hân",
        "phone": 123456789,
        "gender": "Nữ",
        "birthDate": 41289,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Lâm Nguyễn Gia Hân",
        "phone": 123456789,
        "gender": "Nữ",
        "birthDate": 41290,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Lê Khánh Hoàng",
        "phone": 123456789,
        "gender": "Nam",
        "birthDate": 41291,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Kiều Thu Huệ",
        "phone": 123456789,
        "gender": "Nữ",
        "birthDate": 41292,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Hoàng Gia Huy",
        "phone": 123456789,
        "gender": "Nam",
        "birthDate": 41293,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Lê Gia Huy",
        "phone": 123456789,
        "gender": "Nam",
        "birthDate": 41294,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Phạm Quốc Huy",
        "phone": 123456789,
        "gender": "Nam",
        "birthDate": 41295,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Phạm Ngọc Na Hy",
        "phone": 123456789,
        "gender": "Nữ",
        "birthDate": 41296,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Trần Duy Khang",
        "phone": 123456789,
        "gender": "Nam",
        "birthDate": 41297,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Nguyễn Cao Quốc Khánh",
        "phone": 123456789,
        "gender": "Nam",
        "birthDate": 41298,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Nguyễn Vũ Ngân Khánh",
        "phone": 123456789,
        "gender": "Nữ",
        "birthDate": 41299,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Lưu Cao Thiên Khôi",
        "phone": 123456789,
        "gender": "Nam",
        "birthDate": 41300,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Hồ Nhật Khởi",
        "phone": 123456789,
        "gender": "Nam",
        "birthDate": 41301,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Trịnh Ngọc Thiên Lam",
        "phone": 123456789,
        "gender": "Nữ",
        "birthDate": 41302,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Phan Hoàng Long",
        "phone": 123456789,
        "gender": "Nam",
        "birthDate": 41303,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Nguyễn Thảo Ngân",
        "phone": 123456789,
        "gender": "Nữ",
        "birthDate": 41304,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Nguyễn Kim Ngọc",
        "phone": 123456789,
        "gender": "Nữ",
        "birthDate": 41305,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Nguyễn Thị Bảo Ngọc",
        "phone": 123456789,
        "gender": "Nữ",
        "birthDate": 41306,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Phạm Hà Duy Nhân",
        "phone": 123456789,
        "gender": "Nam",
        "birthDate": 41307,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Vũ Nguyễn An Nhiên",
        "phone": 123456789,
        "gender": "Nữ",
        "birthDate": 41308,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Nguyễn Doãn Nam Phong",
        "phone": 123456789,
        "gender": "Nam",
        "birthDate": 41309,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Võ Thiện Phú",
        "phone": 123456789,
        "gender": "Nam",
        "birthDate": 41310,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Trần Lâm Thiên Phúc",
        "phone": 123456789,
        "gender": "Nam",
        "birthDate": 41311,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Hồ Anh Quân",
        "phone": 123456789,
        "gender": "Nam",
        "birthDate": 41312,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Nguyễn Hoàng Chính Tâm",
        "phone": 123456789,
        "gender": "Nam",
        "birthDate": 41313,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Trần Anh Thơ",
        "phone": 123456789,
        "gender": "Nữ",
        "birthDate": 41314,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Quách Hà Minh Thư",
        "phone": 123456789,
        "gender": "Nữ",
        "birthDate": 41315,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Phạm Ngọc Yến Thy",
        "phone": 123456789,
        "gender": "Nữ",
        "birthDate": 41316,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Nguyễn Cao Thanh Trúc",
        "phone": 123456789,
        "gender": "Nữ",
        "birthDate": 41317,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Nguyễn Anh Tuấn",
        "phone": 123456789,
        "gender": "Nam",
        "birthDate": 41318,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Hồ Nguyễn Cát Tường",
        "phone": 123456789,
        "gender": "Nữ",
        "birthDate": 41319,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Nguyễn Ngọc Tú Uyên",
        "phone": 123456789,
        "gender": "Nữ",
        "birthDate": 41320,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Nguyễn Vũ Phương Uyên",
        "phone": 123456789,
        "gender": "Nữ",
        "birthDate": 41321,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Nguyễn Phạm Bảo Vi",
        "phone": 123456789,
        "gender": "Nữ",
        "birthDate": 41322,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Nguyễn Hải Việt",
        "phone": 123456789,
        "gender": "Nam",
        "birthDate": 41323,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Lê Quang Vinh",
        "phone": 123456789,
        "gender": "Nam",
        "birthDate": 41324,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    },
    {
        "fullName": "Trần Đỗ Phương Vy",
        "phone": 123456789,
        "gender": "Nữ",
        "birthDate": 41325,
        "placeOfOrigin": "HCM",
        "classRoomId": "LOP-NEY-yop-150"
    }
]