
#### api này dùng để innit dử liệu tiết học nên  không dùng
POST http://localhost:8080/api/lessons
Content-Type: application/json

[
    {
        "lessonName":"Tiết 1",
        "timeStart":"07:30:00",
        "timeEnd":"08:05:00",
        "active":true
    },
    {
        "lessonName":"Tiết 2",
        "timeStart":"08:05:00",
        "timeEnd":"08:40:00",
        "active":true
    },
    {
        "lessonName":"Ra chơi",
        "timeStart":"08:40:00",
        "timeEnd":"09:10:00",
        "active":false
    },
    {
        "lessonName":"Tiết 3",
        "timeStart":"09:10:00",
        "timeEnd":"10:20:00",
        "active":true
    },
    {
        "lessonName":"Tiết 4",
        "timeStart":"09:45:00",
        "timeEnd":"10:20:00",
        "active":true
    },
    {
        "lessonName":"Tiết 5",
        "timeStart":"10:20:00",
        "timeEnd":"10:55:00",
        "active":true
    },
    {
        "lessonName":"Nghỉ trưa",
        "timeStart":"10:55:00",
        "timeEnd":"14:00:00",
        "active":false
    },
    {
        "lessonName":"Tiết 6",
        "timeStart":"14:00:00",
        "timeEnd":"14:35:00",
        "active":true
    },
    {
        "lessonName":"Tiết 7",
        "timeStart":"14:35:00",
        "timeEnd":"15:10:00",
        "active":true
    },
    {
        "lessonName":"Ra chơi",
        "timeStart":"15:10:00",
        "timeEnd":"15:40:00",
        "active":false
    },
    {
        "lessonName":"Tiết 8",
        "timeStart":"15:40:00",
        "timeEnd":"16:15:00",
        "active":true
    }
]


# các api cho driver sử dụng
#########################################################
POST http://localhost:8080/api/studentAttendenceCheckin
Content-Type: application/json

{
    "studentId":"HS_702-015-591",
    "driverId":"1vUxO"

}
#########################################################
POST http://localhost:8080/api/studentAttendenceCheckout
Content-Type: application/json

{
    "studentId":"2d7c287356f719e555",
    "driverId":"QMFEE"

}
#########################################################
POST http://localhost:8080/api/teacherAttendenceCheckin
Content-Type: application/json

{
    "teacherId":"MnB19",
    "driverId":"QMFEE"

}
#########################################################
POST http://localhost:8080/api/teacherAttendenceCheckout
Content-Type: application/json

{
    "teacherId":"MnB19",
    "driverId":"QMFEE"

}

#########################################################
// các api để test 
//Thêm test vào vị trí /api/test/....
//Thiêm thuộc tính currentTime vào khi gọi api
//ví dụ 
POST http://localhost:8080/api/test/teacherAttendenceCheckin
Content-Type: application/json

{
    "teacherId":"MnB19",
    "driverId":"Kh0sf",
    "currentTime": "09:15:25"

}

### get 1 student 
GET  http://localhost:8080/api/schedule/e0b8a4c75e020db703