export const DMDONVI_CONST = {
    DMDONVI_BEGIN_LOAD:'DMDONVI_BEGIN_LOAD',
    DMDONVI_LOAD_SUCCESS: 'DMDONVI_LOAD_SUCCESS',
    DMDONVI_LOAD_FAIL: 'DMDONVI_LOAD_FAIL',
    DMDONVI_SET_SELECTED: 'DMDONVI_SET_SELECTED'
};