export const DMDOT_CONST = {
    DMDOT_BEGIN_LOAD:'DMDOT_BEGIN_LOAD',
    DMDOT_LOAD_SUCCESS: 'DMDOT_LOAD_SUCCESS',
    DMDOT_LOAD_FAIL: 'DMDOT_LOAD_FAIL',
    DMDOT_SET_SELECTED: 'DMDOT_SET_SELECTED'
};