export const DMNAM_CONST = {
    DMNAM_BEGIN_LOAD:'DMNAM_BEGIN_LOAD',
    DMNAM_LOAD_SUCCESS: 'DMNAM_LOAD_SUCCESS',
    DMNAM_LOAD_FAIL: 'DMNAM_LOAD_FAIL',
    DMNAM_SET_SELECTED: 'DMNAM_SET_SELECTED'
};