const DMNHASANXUAT_CONST = {
    START_LOAD_DMUC_NHASANXUAT: 'START_LOAD_DMUC_NHASANXUAT',
    FINISH_LOAD_DMUC_NHASANXUAT: 'FINISH_LOAD_DMUC_NHASANXUAT',
    FAILED_LOAD_DMUC_NHASANXUAT: 'FAILED_LOAD_DMUC_NHASANXUAT',
};

export default DMNHASANXUAT_CONST;