export const PHIEU_NHAP_XUAT_CONST = {
    LOAD_DANH_SACH_PHIEU_FAIL: "LOAD_DANH_SACH_PHIEU_FAIL",
    SET_DANH_SACH_PHIEU_NHAP: "SET_DANH_SACH_PHIEU_NHAP",
    SET_DANH_SACH_PHIEU_XUAT: "SET_DANH_SACH_PHIEU_XUAT",
};